nodeLinker: node-modules

npmScopes:
  lunasoft-org:
    npmAlwaysAuth: true
    npmAuthToken: ${NODE_AUTH_TOKEN}
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.0.2.cjs

packageExtensions: 
  'storybook-addon-react-router-v6@*':
    peerDependenciesMeta: 
      '@storybook/channels': 
        optional: true
      '@storybook/components':
        optional: true
      '@storybook/core-events':
        optional: true
      '@storybook/manager-api':
        optional: true
      '@storybook/preview-api':
        optional: true
      '@storybook/theming':
        optional: true
    