name: Blank Canvas UI Package
on:
  push:
    tags:
      - 'package.*.*.*'

jobs:
  build:
    name: Blank Canvas UI Package Build
    runs-on: ubuntu-latest

    steps:
      - name: Get semantic version
        id: tempver
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/package.}"

      - uses: actions/checkout@v3

      - name: Yarn install
        run: |
          export NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} 
          yarn set version 4.0.2
          yarn

      - name: Yarn build
        run: |
          export NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} 
          yarn build

      - name: Yarn publish
        run: |
          export NODE_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} 
          yarn npm publish
